In [37]:
import deepchem as dc
import numpy as np
from sklearn.linear_model import LinearRegression
from deepchem.utils.data_utils import load_from_disk, save_to_disk
np.random.seed(0)
# Generating a random data and creating a dataset
X_train, y_train = np.random.randn(5, 1), np.random.randn(5)
train_dataset = dc.data.NumpyDataset(X_train, y_train)
# Wrapping a Sklearn Linear Regression model using DeepChem models API
sklearn_model = LinearRegression()
dc_model = dc.models.SklearnModel(sklearn_model)
dc_model.fit(train_dataset)  # fitting dataset

In [38]:
train_dataset.X

array([[1.76405235],
       [0.40015721],
       [0.97873798],
       [2.2408932 ],
       [1.86755799]])

In [39]:
train_dataset.y

array([-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [40]:
np.random.seed(1)
X_test, y_test = np.random.randn(5, 1), np.random.randn(5)
test_dataset = dc.data.NumpyDataset(X_test, y_test)

In [41]:
dc_model.predict(test_dataset)

array([-0.06376252,  1.08635674,  1.0433657 ,  1.32357718,  0.32659042])

In [42]:
save_to_disk(dc_model, "./model.joblib")

In [43]:
model = load_from_disk("./model.joblib")

In [44]:
model.predict(test_dataset)

array([-0.06376252,  1.08635674,  1.0433657 ,  1.32357718,  0.32659042])